2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_setup.py:_flush():67] Configure stats pid to 85880
2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_setup.py:_flush():67] Loading settings from /home/wyy603/.config/wandb/settings
2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_setup.py:_flush():67] Loading settings from /home/wyy603/Projects/h2oa/h2oa/track/legged_gym/wandb/settings
2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/wyy603/Projects/h2oa/h2oa/track/legged_gym/wandb/offline-run-20250304_194448-48eqdk2t/logs/debug.log
2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/wyy603/Projects/h2oa/h2oa/track/legged_gym/wandb/offline-run-20250304_194448-48eqdk2t/logs/debug-internal.log
2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_init.py:init():761] calling init triggers
2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-04 19:44:48,504 INFO    MainThread:85880 [wandb_init.py:init():784] starting backend
2025-03-04 19:44:48,712 INFO    MainThread:85880 [wandb_init.py:init():788] sending inform_init request
2025-03-04 19:44:48,735 INFO    MainThread:85880 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-04 19:44:48,736 INFO    MainThread:85880 [wandb_init.py:init():803] backend started and connected
2025-03-04 19:44:48,737 INFO    MainThread:85880 [wandb_init.py:init():896] updated telemetry
2025-03-04 19:44:48,737 INFO    MainThread:85880 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-04 19:44:48,841 INFO    MainThread:85880 [wandb_init.py:init():995] starting run threads in backend
2025-03-04 19:44:48,892 INFO    MainThread:85880 [wandb_run.py:_console_start():2377] atexit reg
2025-03-04 19:44:48,893 INFO    MainThread:85880 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-04 19:44:48,893 INFO    MainThread:85880 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-04 19:44:48,893 INFO    MainThread:85880 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-04 19:44:48,893 INFO    MainThread:85880 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-04 19:44:52,414 WARNING MsgRouterThr:85880 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/wyy603/micromamba/envs/h2oa/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/wyy603/micromamba/envs/h2oa/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/wyy603/micromamba/envs/h2oa/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wyy603/micromamba/envs/h2oa/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/wyy603/micromamba/envs/h2oa/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-04 19:44:52,414 INFO    MsgRouterThr:85880 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
